tap "cloudflare/cloudflare"
tap "homebrew/bundle"
tap "homebrew/services"
# Color management engine supporting ICC profiles
brew "little-cms2"
# Companion library to apr, the Apache Portable Runtime library
brew "apr-util"
# Core application library for C
brew "glib"
# Vector graphics library with cross-device output support
brew "cairo"
# International domain name library (IDNA2008, Punycode and TR46)
brew "libidn2"
# C library implementing the SSH2 protocol
brew "libssh2"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# General-purpose scripting language
brew "php"
# Dependency Manager for PHP
brew "composer", link: false
# GNU File, Shell, and Text utilities
brew "coreutils"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Library to load and enumerate PKCS#11 modules
brew "p11-kit"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# OpenType text shaping engine
brew "harfbuzz"
# Image processing and image analysis library
brew "leptonica"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# Blu-Ray disc playback library for media players like VLC
brew "libbluray"
# Framework for layout and rendering of i18n text
brew "pango"
# Secure Reliable Transport
brew "srt"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# GNU compiler collection
brew "gcc"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Git extension for versioning large files
brew "git-lfs"
# Database of common MIME types
brew "shared-mime-info"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Library for reading RAW files from digital photo cameras
brew "libraw"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Modern load testing tool, using Go and JavaScript
brew "k6"
# Provides library functionality for FIDO U2F & FIDO 2.0, including USB
brew "libfido2"
# Utility for directing compilation
brew "make"
# Open source relational database management system
brew "mysql"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP load generator, inspired by rakyll/hey with tui animation
brew "oha"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Theme for zsh
brew "powerlevel10k"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Terminal multiplexer
brew "tmux"
# Version control system designed to be a better CVS
brew "subversion"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Stand alone ad blocker
cask "adguard"
# App to build and share containerised applications and microservices
cask "docker"
# Control your Elgato key lights
cask "elgato-control-center"
# Focusrite interface controller
cask "focusrite-control"
cask "font-hack-nerd-font"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# WordPress local development tool by Flywheel
cask "local"
# Open-source software for live streaming and screen recording
cask "obs"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Collaboration platform for API development
cask "postman"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Digital design and prototyping platform
cask "sketch"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Open-source BitTorrent client
cask "transmission"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Resources for Wacom tablets
cask "wacom-tablet"
vscode "ardenivanov.svelte-intellisense"
vscode "astro-build.astro-vscode"
vscode "bmewburn.vscode-intelephense-client"
vscode "bradlc.vscode-tailwindcss"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "firsttris.vscode-jest-runner"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-execution"
vscode "graphql.vscode-graphql-syntax"
vscode "johnbillion.vscode-wordpress-hooks"
vscode "lehni.vscode-fix-checksums"
vscode "mechatroner.rainbow-csv"
vscode "medo64.render-crlf"
vscode "mkxml.vscode-filesize"
vscode "ms-playwright.playwright"
vscode "ms-vsliveshare.vsliveshare"
vscode "prisma.prisma"
vscode "qwtel.sqlite-viewer"
vscode "ryu1kn.partial-diff"
vscode "streetsidesoftware.code-spell-checker"
vscode "svelte.svelte-vscode"
vscode "unifiedjs.vscode-mdx"
vscode "usernamehw.errorlens"
vscode "vscodevim.vim"
vscode "wix.vscode-import-cost"
vscode "wordpresstoolbox.wordpress-toolbox"
vscode "yoavbls.pretty-ts-errors"
